package com.deliverytech.delivery_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.Data;                 
import lombok.NoArgsConstructor;  
import lombok.AllArgsConstructor;
import lombok.Builder;   

@Entity                             // Marks this class as a JPA entity
@Data                               // Lombok annotation to generate getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor                  // Lombok annotation to generate a no-argument constructor
@AllArgsConstructor                 // Lombok annotation to generate a constructor with all fields as parameters
@Builder                            // Lombok annotation to provide a builder pattern for this class
public class Cliente {

    @Id                             // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY) // Specifies that the primary key will be generated by the database
    private Long id;

    @Column(nullable = false)
    private String nome;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private String telefone;

    @Builder.Default
    private Boolean ativo = true;

}
